name: publish

on:
  push:
    tags:
      - 'bepinex-v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4

      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0'

      - name: build mod dll
        run: dotnet build ReArmature/ReArmature.csproj -c Release

      - name: Stage Artifacts & Extract Version
        run: |
          mkdir -p dist/BepInEx/plugins/
          find ReArmature/bin/Release/ -name "ReArmature.dll" -exec cp {} dist/BepInEx/plugins/ \;
          RAW_VER="${{ github.ref_name }}"
          CLEAN_VER="${RAW_VER#bepinex-v}"
          echo "MOD_VERSION=$CLEAN_VER" >> $GITHUB_ENV

      - name: upload to thunderstore
        uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          token: ${{ secrets.THUNDERSTORE_TOKEN }}
          community: resonite
          namespace: catshark
          name: rearmature
          version: ${{ env.MOD_VERSION }}
          description: "reassign a skinnedmeshrenderer to a new armature"
          path: 'dist'